export const PANEL_SIZE = 280;
export const EFFECT_PADDING = 30;
export const TEXTURE_SIZE = PANEL_SIZE + EFFECT_PADDING * 2;
export const SOURCE_TEXTURE_SCALE = 2;
export const SOURCE_TEXTURE_SIZE = TEXTURE_SIZE * SOURCE_TEXTURE_SCALE;
